# Generated by Django 5.0.1 on 2024-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], max_length=50)),
                ('to_currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
