# Generated by Django 5.0.1 on 2024-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
