# Generated by Django 5.0.1 on 2024-01-30 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_myuser_name_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Пароль должен содержать не менее 8 символов', regex='^.{8,}$')], verbose_name='пароль'),
        ),
    ]
